version: "3"
services:
  svelte-pokedex:
    image: node:20
    container_name: svelte-pokedex
    volumes:
      - ./:/home/svelte-pokedex
    working_dir: /home/svelte-pokedex
    ports:
      - 5173:5173
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Paris
      - HOST=0.0.0.0
    restart: unless-stopped
    tty: true
